# Generated by Django 4.2.5 on 2023-09-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumbnail_sizes', models.CharField(max_length=255)),
                ('include_original_link', models.BooleanField(default=False)),
                ('generate_expiring_links', models.BooleanField(default=False)),
            ],
        ),
    ]
