# Generated by Django 4.2.5 on 2023-09-20 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customtier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.customtier'),
        ),
    ]
